language: "en"
pipeline:
    - name: "tokenizer_whitespace"
    - name: "nlp_spacy"
    - name: "tokenizer_spacy"
    - name: "intent_featurizer_count_vectors"
    - name: "intent_classifier_tensorflow_embedding"
    - name: "intent_featurizer_spacy"
    - name: "intent_classifier_sklearn"
    - name: "ner_crf"
    - name: "ner_synonyms"